spring.application.name=devProject
spring.thymeleaf.cache=false

# datasource (oracle)
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=hr
spring.datasource.password=hr1234

# Mybatis 설정 - xml location
mybatis.mapper-locations=classpath:templates/mapper/*.xml